SebLabbate/Melomane

- app/views/pages/home.html.erb
- app/views/shared/_navbar.html.erb
created a dashboard page with nothing and fix somu bugs and links on navbar
> some fixes

- app/assets/stylesheets/components/_avatar.scss
- app/assets/stylesheets/pages/_dashboard.scss
- app/assets/stylesheets/pages/_index.scss
- app/views/pages/dashboard.html.erb
> dashboard terminator

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/pages/_upcoming_gigs.scss
- app/controllers/user_gigs_controller.rb
- app/policies/user_gig_policy.rb
- app/views/gigs/index.html.erb
- app/views/shared/_navbar.html.erb
- app/views/user_gigs/index.html.erb
- config/routes.rb
Upcoming gigs is working 🚀
You can add a gig from gigs page
> upcoming gigs page

- app/controllers/application_controller.rb
- app/controllers/user_gigs_controller.rb
- app/controllers/users_controller.rb
- app/views/pages/dashboard.html.erb
- db/migrate/20230306204817_remove_date_from_gigs.rb
- db/migrate/20230306204943_add_date_to_gigs.rb
- db/schema.rb
Dashbord upcoming gigs is reading from gigs. So when gig is added , it shows in dashboards upcoming gigs
> Dashboard v1

- app/assets/stylesheets/pages/_index.scss
- app/assets/stylesheets/pages/_user_gigs.scss
- app/views/past_gigs/index.html.erb
- app/views/user_gigs/index.html.erb
- config/routes.rb
button is not fully functional yet
> add an attended button in user gigs, created index page for past_gigs

- app/controllers/user_gigs_controller.rb
- app/views/user_gigs/index.html.erb
- db/migrate/20230309155846_create_active_storage_tables.active_storage.rb
- db/schema.rb
> destroy working

- app/views/pages/dashboard.html.erb
- db/schema.rb
- db/seeds.rb
fixed seeds and changed hardcoded user ids and user gig ids
> Fixed seeds

- app/assets/stylesheets/pages/_dashboard.scss
- app/controllers/pages_controller.rb
- app/views/pages/dashboard.html.erb
- app/views/shared/_navbar.html.erb
- app/views/user_gigs/past_gigs.html.erb
> dashboard front-ends

- app/assets/stylesheets/pages/_dashboard.scss
- app/views/pages/dashboard.html.erb
> Dash board

- app/assets/stylesheets/pages/_usergigshow.scss
- app/views/user_gigs/show.html.erb
- app/views/user_gigs/show_test.html.erb
> post gigs show page frontend

- app/assets/stylesheets/pages/_usergigshow.scss
- app/controllers/user_gigs_controller.rb
- app/views/user_gigs/edit.html.erb
- app/views/user_gigs/show.html.erb
> user gigs past show page

- app/assets/stylesheets/pages/_usergigshow.scss
- app/views/user_gigs/show.html.erb
- app/views/user_gigs/show_test.html.erb
Upcoming gigs show page-> 
Looks the same as past gigs, missing other suggestions
> user gigs upcoming gigs show

- app/assets/stylesheets/pages/_usergigshow.scss
- app/views/user_gigs/show.html.erb
- app/views/user_gigs/show_test.html.erb
> show pages for demo

- app/assets/stylesheets/pages/_usergigshow.scss
- app/controllers/comments_controller.rb
- app/policies/comment_policy.rb
- app/views/user_gigs/_show_past_gig.html.erb
- config/routes.rb
- package.json
- yarn.lock
Uploaded images to past user gigs
> upload pictures to a gig

- app/controllers/comments_controller.rb
- app/models/comment.rb
- app/views/comments/new.html.erb
- app/views/user_gigs/_show_past_gig.html.erb
- config/environments/development.rb
> video player working

- app/assets/stylesheets/pages/_usergigshow.scss
- app/views/user_gigs/_show_past_gig.html.erb
- package-lock.json
- package.json
- yarn.lock
Added zoom in effect on images
> zoom in on pictures

- app/assets/stylesheets/pages/_usergigshow.scss
- app/views/user_gigs/_show_past_gig.html.erb
> gallery fix

- Gemfile.lock
- app/assets/stylesheets/application.scss
- app/assets/stylesheets/components/_forms.scss
- app/controllers/user_gigs_controller.rb
- app/models/gig.rb
- app/views/comments/new.html.erb
- app/views/gigs/new.html.erb
- app/views/user_gigs/_show_past_gig.html.erb
- app/views/user_gigs/edit.html.erb
Fixed edit & destroy methods for user gig page
Did some changes to memories, edit gig and create gig forms
> fixed edit & destroy for user gigs, form fixes

- app/assets/stylesheets/components/_buttons.scss
- app/assets/stylesheets/components/_map.scss
- app/assets/stylesheets/pages/_upcoming_gigs.scss
- app/javascript/controllers/index.js
- app/views/shared/_navbar.html.erb
- app/views/user_gigs/_show_upcoming_gig.html.erb
- app/views/user_gigs/upcoming_gigs.html.erb
Message appears when there is no gig in upcoming gigs
> upcoming gigs message

- app/assets/stylesheets/components/_forms.scss
- app/javascript/controllers/index.js
- app/javascript/controllers/modal_controller.js
- app/views/comments/new.html.erb
- app/views/layouts/application.html.erb
- app/views/user_gigs/_show_past_gig.html.erb
- app/views/user_gigs/edit.html.erb
- app/views/user_gigs/upcoming_gigs.html.erb
Changed forms to modal for:
- Adding new memories
- Editing gigs
> changed edit & memories forms to modals

- app/assets/stylesheets/pages/_usergigshow.scss
- app/views/user_gigs/_show_past_gig.html.erb
- app/views/user_gigs/upcoming_gigs.html.erb
Small fixes on past user gigs show page
> small fixes on past user_gigs show

- app/assets/stylesheets/pages/_usergigshow.scss
- app/views/user_gigs/_show_upcoming_gig.html.erb
> fixued suggested artists section

- app/controllers/gigs_controller.rb
- app/controllers/user_gigs_controller.rb
- app/models/gig.rb
- app/models/user_gig.rb
- app/views/gigs/new.html.erb
- app/views/pages/dashboard.html.erb
- app/views/user_gigs/_show_past_gig.html.erb
- app/views/user_gigs/past_gigs.html.erb
- app/views/user_gigs/upcoming_gigs.html.erb
upload image when creating new gig
> uploading picture when creating artist

- app/views/shared/_navbar.html.erb
> changed avatar

- app/views/gigs/new.html.erb
added required fields in forms
> added asterisk to the forms

- app/controllers/gigs_controller.rb
- app/views/gigs/index.html.erb
Reverts SebLabbate/Melomane#141
> Revert "sorted"
